(function(){'use strict';var g;var h={i:function(a,b,c){if("undefined"!=typeof c){var f=h.c();f&&f.saveStyleOverride(a,b,c);a.style[b]=c}},f:function(a,b,c){c?a.classList.add(b):a.classList.remove(b)},v:function(a,b){if("undefined"!=typeof b){var c=h.c();c&&c.saveInitialText(a);a.textContent=b;c&&c.applyStylePreservation(a)}},u:function(a,b){if("undefined"!=typeof b){var c=h.c();c&&c.saveInitialText(a);a.innerHTML=b;c&&c.applyStylePreservation(a)}},show:function(a,b){a.style.display=b?"":"none"},setAttribute:function(a,b,c){"undefined"!=
typeof c&&a.setAttribute(b,c)},c:function(){return document.querySelector("gwd-text-helper")}};window.Binder=h;h.setText=h.v;h.setStyle=h.i;h.setHtml=h.u;h.addOrRemoveClassName=h.f;h.show=h.show;h.setAttribute=h.setAttribute;var l={limit:function(a,b){return b?a&&a.length&&("string"==typeof b&&(b=parseInt(b,10)),!isNaN(b))?a.slice(0,b):a:a},pluck:function(a,b){if(a){var c=b.split(".");return a.map(function(a){if(1==c.length)return a[c[0]];var b=a;c.forEach(function(a){b&&(b=b[a])});return b})}return[]},join:function(a,b){return a?a.join(b||","):""},s:function(a,b){return l.join(l.pluck(a,b))},toUpperCase:function(a){return a?a.toUpperCase():a},toLowerCase:function(a){return a?a.toLowerCase():a},A:function(a){if("undefined"!=
typeof a)return a+"px"},w:function(a){return a?a.replace(/0x/,"#"):a}};window.Formatter=l;l.limit=l.limit;l.toUpperCase=l.toUpperCase;l.toLowerCase=l.toLowerCase;l.toPixelValue=l.A;l.toHex=l.w;l.pluck=l.pluck;l.join=l.join;l.pluckAndJoin=l.s;var n=/^bind-/,p=/^style-/,q=/^class-/,r=/^each-/,t=/-([a-z])/g;function u(a){return String(a).replace(t,function(a,c){return c.toUpperCase()})}function v(a){return!(!a||!n.test(a.name))}function w(a){return!(!a||0!=a.name.indexOf("bind-each"))}function x(a){Array.prototype.slice.call(a.attributes).filter(w).forEach(function(b){a.removeAttribute(b.name)})}var y=function(){};goog.inherits(y,HTMLElement);g=y.prototype;
g.createdCallback=function(){this.a={text:"setText",html:"setHtml",show:"show"};this.b={limit:"limit",pixelvalue:"toPixelValue",uppercase:"toUpperCase",lowercase:"toLowerCase",hex:"toHex",pluck:"pluck",join:"join",pluckandjoin:"pluckAndJoin"};this.h=!1};g.getBinder=function(){return h};g.getFormatter=function(){return l};
g.bindData=function(a,b){b=b||Array.prototype.slice.call(document.querySelectorAll("*"));var c=document.querySelector("meta[name=environment]");this.h="gwd-adwords"==(c?c.getAttribute("content"):"");b.forEach(this.j.bind(this,a))};g.j=function(a,b){if(!b.hasAttribute("gwd-bind-each-template")){for(var c,f=Array.prototype.slice.call(b.attributes),d=f.length,e=0;e<d;e++)if(w(f[e])){c=f[e];break}a=this.m.bind(this,b,a);c?a(c):f.filter(v).forEach(a)}};
g.m=function(a,b,c){var f=c.name,d=f.replace(n,"");var e=this.getBinder();if(p.test(d)){var m=d.replace(p,"");e=e.i.bind(null,a,u(m))}else q.test(d)?(m=d.replace(q,""),e=e.f.bind(null,a,m)):r.test(d)?(e=d.replace(r,""),e=this.l.bind(this,a,e,b)):e=this.a[d]&&"function"==typeof e[this.a[d]]?e[this.a[d]].bind(null,a):window.gwd&&window.gwd.binders&&"function"==typeof window.gwd.binders[d]?window.gwd.binders[d]:e.setAttribute.bind(null,a,d);f=a.getAttribute(f);b=(-1!==f.indexOf("|")?this.o.bind(this,
b,f):this.g.bind(this,b,f)).call(a);"exit-override-url"==d&&(d=(d=c.value)&&d.match(/product\.\d+/i)?(d=d.match(/product\.(\d+)/i))&&d[1]?parseInt(d[1],10):null:null,null!=d&&a.setAttribute("product-index",d),this.h&&a.setAttribute("exit-id",c.value.replace(/\./g,"_")));e.apply(a,[b])};
g.l=function(a,b,c,f){var d=a.parentNode;if(d){var e=a.cloneNode(!0);x(e);for(var m=[],k=0;f&&k<f.length;k++)m.push(e.cloneNode(!0));k={instances:m};e=document.createEvent("CustomEvent");e.initCustomEvent("gwdbindeachcloned",!0,!0,k);a.dispatchEvent(e);e=document.createComment("gwd-bind-each-placeholder");d.insertBefore(e,a);d.removeChild(a);z(a);if(f&&0!=f.length){for(k=0;k<f.length;k++){c[b]=f[k];a=m[k];a.setAttribute("gwd-repeat-index",k);c.$index=k;var A=Array.prototype.slice.call(a.querySelectorAll("*"));
this.bindData(c,A.concat(a));d.insertBefore(a,e)}delete c[b]}}};var z=function(a){a.setAttribute("gwd-bind-each-template","");Array.prototype.slice.call(a.querySelectorAll("*")).forEach(function(a){a.setAttribute("gwd-bind-each-template","")})};y.prototype.g=function(a,b){if(a){if(b){b=b.replace("[",".");b=b.replace("]","");var c=a;b.split(".").forEach(function(a){c&&(c=c[a])});return c}return a}};
y.prototype.o=function(a,b){if(!b)return a;b=b.split("|");var c=b.shift().trim();c=this.g(a,c);if("undefined"!=typeof c){for(a=0;a<b.length;a++){var f=b[a].trim().split(" "),d=f.shift().trim();f.unshift(c);var e=this.getFormatter();c=this.b[d]&&"function"==typeof e[this.b[d]]?e[this.b[d]].apply(this,f):window.gwd&&window.gwd.formatters&&"function"==typeof window.gwd.formatters[d]?window.gwd.formatters[d].apply(this,f):c}return c}};y.prototype.attributeChangedCallback=function(){};
document.registerElement("gwd-data-binder",{prototype:y.prototype});}).call(this);
