(function(){'use strict';var e;var k=function(a,b){a=parseInt(a.getAttribute("gwd-min-font-size-px"),10);isNaN(a)&&(a=b);return a},l=function(a,b){switch(a.getAttribute("gwd-fitting-truncate")){case "true":return!0;case "false":return!1;default:return b}};var p=function(a){var b=!1,c=null;return function(){b=!0;c||(b&&(a(),b=!1),c=setTimeout(function(){c=null;b&&(a(),b=!1)},100))}};var q=/[^\s\xA0]/,t=function(a){return(a=r.exec(a||""))?parseFloat(a[1]):null},r=/^(\d+|\d*\.\d+)px$/i,w=/^(\d+|\d*\.\d+)em$/i;function x(){this.a=[];this.s=10;this.A=!1}
x.prototype.fit=function(a){var b=[];a.forEach(function(a){if(this.a.every(function(b){return b.element!=a})&&!a.hasAttribute("gwd-dont-fit")){y(a);var c=z(this,a);this.a.push(c);b.push(c)}},this);b.forEach(function(a){var b={originalFontSize:a.i,fittedFontSizePx:a.B,wasTruncated:null!=a.j};null!=a.j&&(b.originalInnerHTML=a.j);a=a.element;if(b){var c=document.createEvent("CustomEvent");c.initCustomEvent("gwdtextfitted",!0,!0,b)}else c=document.createEvent("Event"),c.initEvent("gwdtextfitted",!0,!0);
a.dispatchEvent(c)})};
var A=function(a){a.a.forEach(function(a){a.element.style.fontSize=a.i});a.a=[]},B=function(a,b){b.forEach(function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(c.element==a){c.element.style.fontSize=c.i;this.a.splice(b,1);break}}}.bind(a))},z=function(a,b){var c=window.getComputedStyle(b),d=t(c.fontSize)||24,g=k(b,a.s),h=l(b,a.A);a=b.style.fontSize;c=null;a:{for(var u=b.clientWidth,f=b.clientHeight;d>=g;d--)if(b.style.fontSize=""+d+"px",!(b.scrollHeight>f||b.scrollWidth>u)){g=d;break a}if(h){c=
b.innerHTML;h=b.textContent;d=h.length;for(var m=1,v=0;10>v;v++){var n=Math.floor((d+m)/2);b.textContent=h.slice(0,n)+"\u2026";b.scrollHeight>f||b.scrollWidth>u?d=n:m=n}b.innerHTML=h.slice(0,m)+"\u2026"}}return{element:b,i:a,B:g,j:c}},y=function(a){function b(a,c){a.hasAttribute("gwd-dont-fit")||Array.prototype.forEach.call(a.children,function(a){var d=window.getComputedStyle(a).fontSize,f=t(d);if(f)f!=c&&(d=f/c,a.style.fontSize=d+"em");else if(d=(f=w.exec(d||""))?parseFloat(f[1]):null)f=d*c;else return;
b(a,f)})}var c=t(window.getComputedStyle(a).fontSize);null!=c&&b(a,c)};var C=function(a){this.w=a;this.h=new WeakMap;this.m=new WeakMap};C.prototype.saveInitialText=function(a){for(var b=document.createNodeIterator(a,NodeFilter.SHOW_TEXT,null,!1),c=null,d;d=b.nextNode();)if(q.test(d.textContent)){c=d;break}if(c&&(b=c.parentNode,b!=a)){a.setAttribute("gwd-dont-fit","");for(c=b;c.parentNode!=a;)c=c.parentNode;this.h.set(a,{f:c,parent:b})}};
C.prototype.applyStylePreservation=function(a){if(this.h.get(a)){a.ownerDocument.compareDocumentPosition(a)&Node.DOCUMENT_POSITION_DISCONNECTED||D(this,a);var b=document.createElement("gwd-attached");a.appendChild(b);var c=function(){b.removeEventListener("attached",c);D(this,a);a.removeChild(b)}.bind(this);b.addEventListener("attached",c)}};
var D=function(a,b){var c=a.h.get(b),d=a.m.get(b)||{};if(c){c.f.style.display="none";b.insertBefore(c.f,b.firstChild);try{B(a.w,[b]);var g=getComputedStyle(c.parent);E.forEach(function(a){var c=g.getPropertyValue(a);!d.hasOwnProperty(a)&&c&&b.style.setProperty(a,c,"")});b.removeAttribute("gwd-dont-fit");a.w.fit([b])}finally{b.removeChild(c.f)}}};C.prototype.saveStyleOverride=function(a,b,c){var d=this.m.get(a)||{};d[b]=c;this.m.set(a,d)};var E="color font-family font-size font-style font-weight font-stretch text-align white-space".split(" ");var F=function(){};goog.inherits(F,HTMLElement);e=F.prototype;e.createdCallback=function(){this.b=new x;this.g=":not(*)";this.l=new C(this.b);this.u=this.F.bind(this);this.c=this.D.bind(this);document.addEventListener("pagetransitionstart",this.u);document.addEventListener("adinitialized",this.c);["fit-font-size-for-selector","gwd-fitting-truncate","gwd-min-font-size-px"].forEach(this.o,this);this.v=p(this.C.bind(this))};
e.detachedCallback=function(){document.removeEventListener("pagetransitionstart",this.u);document.removeEventListener("adinitialized",this.c);window.removeEventListener("resize",this.v,!1)};e.D=function(){document.removeEventListener("adinitialized",this.c);this.refitAll();window.addEventListener("resize",this.v,!1)};e.F=function(a){"gwd-pagedeck"==a.target.getAttribute("is").toLowerCase()&&this.fit(Array.prototype.slice.call(a.target.querySelectorAll(this.g)))};e.saveInitialText=function(a){this.l.saveInitialText(a)};
e.applyStylePreservation=function(a){this.l.applyStylePreservation(a)};e.saveStyleOverride=function(a,b,c){this.l.saveStyleOverride(a,b,c)};e.o=function(a){var b=this.getAttribute(a);switch(a){case "fit-font-size-for-selector":this.g=b||":not(*)";break;case "gwd-min-font-size-px":this.b.s=k(this,10);break;case "gwd-fitting-truncate":this.b.A=l(this,!1)}};e.fit=function(a){this.b.fit(a||Array.prototype.slice.call(document.querySelectorAll(this.g)))};e.attributeChangedCallback=function(a){this.o(a)};
e.C=function(){this.refitAll()};e.refitAll=function(){A(this.b);this.fit()};document.registerElement("gwd-text-helper",{prototype:F.prototype});}).call(this);
